title: <p align = 'center' > Kaylyn Vo </p>

logo: "/images/picture.png?raw=true" 

description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align = 'center'>
  <a href="resume/VoKaylynResume.pdf'>Resume</a>|
  <a href="https://github.com/vkaylyn">GitHub</a>|
  <a href="https://www.linkedin.com/in/kaylyn-vo-244b0017a/">LinkedIn</a>
  
  </p>
 
  <p align='justify'>
  I am a second year Master's Student of Statistics at San Jose State University.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

